# Generated by Django 5.2 on 2025-05-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_area", models.FloatField()),
                ("living_area", models.FloatField()),
                ("floor", models.IntegerField()),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("Железнодорожный", "Железнодорожный район"),
                            ("Кировский", "Кировский район"),
                            ("Ленинский", "Ленинский район"),
                            ("Октябрьский", "Октябрьский район"),
                            ("Свердловский", "Свердловский район"),
                            ("Советский", "Советский район"),
                            ("Центральный", "Центральный район"),
                        ]
                    ),
                ),
                ("price", models.FloatField()),
            ],
        ),
    ]
